name: Android Debug Build

on:
  push:
    branches:
      - main
      - master
      - dev

  pull_request:
    branches:
      - main
      - master

  workflow_dispatch:

jobs:
  build-debug:
    runs-on: ubuntu-latest

    steps:
      # Checkout source
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setup Java
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      # Permission gradlew
      - name: Grant execute permission
        run: chmod +x gradlew

      # Cache Gradle
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Build Debug APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      # Upload APK
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: Musicmax-Debug-APK
          path: app/build/outputs/apk/debug/*.apk

      # Upload Logs jika gagal
      - name: Upload Build Reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: Build-Logs
          path: |
            **/build/reports/
            **/build/outputs/logs/
